### ISSUE TITLE
`ISphereXEngine` doesn't implement `SphereXEngine` method to `removeAllowedSender`

### ISSUE THREAD

**Issue by Ikpong-Joseph** [spherex-xyz/spherex-contracts#57]
Hello, I'm in an audit of Wildcat Finance and noticed that engine can add senders on chain via `ISphereXEngine` interface but has no method  to remove them.

Also the `ISphereXEngine` interface doesn't implement all functions in the `SphereXEngine`.

Was this intended? 

Thanks for your time.

**Comment by sfeyal** [comment]
currently we dont allow to remove contracts from within a protected contract (in this case a factory), adding protection is always welcome but removing protection can cause holes in protection and might be abused by malicious actor, nonetheless the admin\operator of the engine can directly remove contracts.
regarding the second question, yes,  ISphereXEngine includes only the functions needed to communicate with the engine from a protected contract.
